# Source: fluentbit-resource/templates/fluentbit/configmap-files.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-configmap
  namespace: lma
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
  labels:
    app: fluentbit-resource-operator
    
    chart: fluentbit-resource-1.1.0
    release: "fluentbit"
    heritage: "Helm"
data:
  create_user_taco-es.sh: |-
    #!/bin/sh
    set -ex
    curl -k -u elastic:${ELASTIC_PW} -X POST ${ES_URL}/_security/user/$1 -H 'Content-Type: application/json' -d'
    {
      "password" : "password",
      "roles" : [ "superuser" ],
      "full_name" : "LMA user by TACO",
      "email" : "taco@taco.com",
      "metadata" : {
        "intelligence" : 7
      }
    }
    '
  create_template_taco-es.sh: |-
    #!/bin/sh
    set -ex
    
    ### Index Lifecycle Management
    echo "trying to setting policy hot-delete-14days..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_ilm/policy/hot-delete-14days" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/ilm-hot-delete-14days_taco-es.json
    echo "trying to setting policy hot-delete-7days..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_ilm/policy/hot-delete-7days" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/ilm-hot-delete-7days_taco-es.json
    echo "trying to setting policy hot-delete-3hour..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_ilm/policy/hot-delete-3hour" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/ilm-hot-delete-3hour_taco-es.json
    ### Templates
    echo "trying to setting Template platform..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_template/platform" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/template-platform_taco-es.json
    echo "trying to setting Template application..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_template/application" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/template-application_taco-es.json
    echo "trying to setting Template syslog..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/_template/syslog" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/template-syslog_taco-es.json
    ### generate first index
    echo "trying to create initial index container-000001..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/container-000001" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/index-container_taco-es.json
    echo "trying to create initial index platform-000001..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/platform-000001" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/index-platform_taco-es.json
    echo "trying to create initial index syslog-000001..."
    curl -k -u elastic:${ELASTIC_PW} -X PUT "${ES_URL}/syslog-000001" \
      -H 'Content-Type:application/json' -H 'kbn-xsrf:true' -d @/tmp/index-syslog_taco-es.json
  ilm-hot-delete-14days_taco-es.json: |- 
    {"policy":{"phases":{"delete":{"actions":{"delete":{}},"min_age":"14d"},"hot":{"actions":{"rollover":{"max_age":"1d","max_docs":5000000000,"max_size":"30gb"},"set_priority":{"priority":100}}}}}}
  ilm-hot-delete-7days_taco-es.json: |- 
    {"policy":{"phases":{"delete":{"actions":{"delete":{}},"min_age":"7d"},"hot":{"actions":{"rollover":{"max_age":"1d","max_docs":5000000000,"max_size":"30gb"},"set_priority":{"priority":100}}}}}}
  ilm-hot-delete-3hour_taco-es.json: |- 
    {"policy":{"phases":{"delete":{"actions":{"delete":{}},"min_age":"3h"},"hot":{"actions":{"rollover":{"max_age":"1h","max_docs":5000000000,"max_size":"30gb"},"set_priority":{"priority":100}}}}}}
  template-platform_taco-es.json: |-
    {"index_patterns":"platform*","settings":{"index.lifecycle.name":"hot-delete-14days","index.lifecycle.rollover_alias":"platform","number_of_replicas":1,"number_of_shards":3,"refresh_interval":"30s"}}
  template-application_taco-es.json: |-
    {"index_patterns":"container*","settings":{"index.lifecycle.name":"hot-delete-3hour","index.lifecycle.rollover_alias":"container","number_of_replicas":1,"number_of_shards":3,"refresh_interval":"30s"}}
  template-syslog_taco-es.json: |-
    {"index_patterns":"syslog*","settings":{"index.lifecycle.name":"hot-delete-14days","index.lifecycle.rollover_alias":"syslog","number_of_replicas":1,"number_of_shards":2,"refresh_interval":"30s"}}
  index-container_taco-es.json: |-
    { "aliases": { "container":{ "is_write_index": true } } }
  index-platform_taco-es.json: |-
    { "aliases": { "platform":{ "is_write_index": true } } }
  index-syslog_taco-es.json: |-
    { "aliases": { "syslog":{ "is_write_index": true } } }
